### ISSUE TITLE
Support for JRodrigoTech's Flash Carts

### ISSUE THREAD

**Issue by weux** [insidegadgets/GBxCart-RW#17]
I made a couple flash carts using junk games, the adapter board linked below, and some AM29F016 and AM29F032 flash. The AM29F016 ones work fine, but I’m not able to get the AM29F032 to work.

Would it be possible to add support for AM29F032 chips using this adapter? 

https://github.com/JRodrigoTech/FLASH-ROM-Adapter-for-GameBoy

**Comment by insidegadgets** [comment]
Hi there,

The AM29F032 should work with the AM29F016 but just be limited to 2MB - we can increase that limit. Can you confirm the issue that happens when you try to flash it?

If you don't get past the chip erase part, try running the flash id program which will let you know if the flash chip is responding. If it isn't responding, you should re-check your wiring, re-seat the cart, re-flow the flash chip and lastly try a different flash chip or cart: https://flashcartdb.com/index.php/GBxCart_RW_Manual#If_you_can.27t_write_to_a_flash_cart

**Comment by weux** [comment]
Thanks, that tool made troubleshooting much easier. I should have read the manual to begin with. As far as I can tell the first chip I tried is dead. I swapped it out for another AM29F032 and I was able to write and read back a 2MB rom. If you're able to increase the limit to 4MB I'd really appreciate it.

**Comment by insidegadgets** [comment]
Sure, support for 4MB has now been added to Flasher v1.30
